version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    versioning-strategy: 'auto'
    allow:
      - dependency-type: 'development'
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore(deps-dev)'
      include: 'scope'
    open-pull-requests-limit: 10
    target-branch: 'dev'
    lockfile-only: false
    labels:
      - 'dependencies'
      - 'devDependencies'
    groups:
      dev-dependencies:
        dependency-type: 'development'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    files:
      - 'package.json'
      - 'pnpm-lock.yaml'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'dev'
    groups:
      actions-minor:
        update-types:
          - minor
          - patch
