# fly.toml app configuration file generated for still-meadow-5602 on 2023-07-30T09:28:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "still-meadow-5602"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
