name: Staging App
on:
  # Run this workflow on every PR event. Existing review apps will be updated when the PR is updated.
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_PREVIEW }}
  # Set these to your Fly.io organization and preferred region.
  FLY_REGION: ams
  FLY_ORG: personal
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  DEMO_PASSWORD: ${{ secrets.DEMO_PASSWORD }}
  DEMO_EMAIL: ${{ secrets.DEMO_EMAIL }}
  DOCUMENTAI_PROCESSOR_NAME: ${{ secrets.DOCUMENTAI_PROCESSOR_NAME }}
  DOCUMENTAI_ENDPOINT: ${{ secrets.DOCUMENTAI_ENDPOINT }}
  VITE_POCKETBASE_URL: ${{ secrets.VITE_POCKETBASE_URL }}

jobs:
  review_app:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}

    # Deploying apps with this "review" environment allows the URL for the app to be displayed in the PR UI.
    # Feel free to change the name of this environment.
    environment:
      name: review
      # The script in the `deploy` sets the URL output for each review app.
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Deploy PR app to Fly.io
        id: deploy
        uses: JoeyRichter/fly-pr-review-apps@main
        with:
          build_secrets: |
            VITE_POCKETBASE_URL=${{ secrets.VITE_POCKETBASE_URL }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            DEMO_PASSWORD=${{ secrets.DEMO_PASSWORD }}
            DEMO_EMAIL=${{ secrets.DEMO_EMAIL }}
            DOCUMENTAI_PROCESSOR_NAME=${{ secrets.DOCUMENTAI_PROCESSOR_NAME }}
            DOCUMENTAI_ENDPOINT=${{ secrets.DOCUMENTAI_ENDPOINT }}

      - name: Clean up GitHub environment
        uses: strumwolf/delete-deployment-environment@v3
        if: ${{ github.event.action == 'closed' }}
        with:
          # ⚠️ The provided token needs permission for admin write:org
          token: ${{ secrets.TAIJOBI_GITHUB_TOKEN }}
          environment: pr-${{ github.event.number }}
